name        : desktop-file-utils
version     : 0.23
release     : 8
source      :
    - https://freedesktop.org/software/desktop-file-utils/releases/desktop-file-utils-0.23.tar.xz : 6c094031bdec46c9f621708f919084e1cb5294e2c5b1e4c883b3e70cb8903385
homepage    : http://freedesktop.org/wiki/Software/desktop-file-utils
license     :
    - GPL-2.0
summary     : Utilities required for working with Desktop entries
component   : desktop.core
description : |
    The Desktop File Utils package contains command line utilities for working with Desktop entries. These utilities are used by Desktop Environments and other applications to manipulate the MIME-types application databases and help adhere to the Desktop Entry Specification.
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
