name       : desktop-file-utils
version    : '0.26'
release    : 11
source     :
    - https://freedesktop.org/software/desktop-file-utils/releases/desktop-file-utils-0.26.tar.xz : b26dbde79ea72c8c84fb7f9d870ffd857381d049a86d25e0038c4cef4c747309
homepage   : http://freedesktop.org/wiki/Software/desktop-file-utils
license    : GPL-2.0-or-later
summary    : Utilities required for working with Desktop entries
component  : desktop.core
description: |
    The Desktop File Utils package contains command line utilities for working with Desktop entries. These utilities are used by Desktop Environments and other applications to manipulate the MIME-types application databases and help adhere to the Desktop Entry Specification.
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
check      : |
    %ninja_check
